- name: test
  hosts: all

  vars:
    v_var_file:     '/home/opc/Terraform/terraform.tfvars'

  tasks:
    - include_tasks: terraform/create-vcn.yaml
      vars:
        v_varfile:  '{{ v_var_file }}'

    - include_tasks: terraform/destroy-vcn.yaml
      vars:
        v_varfile:  '{{ v_var_file }}'
